# Generated by Django 4.2.10 on 2024-03-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='source',
        ),
    ]
