# Generated by Django 4.2.10 on 2024-03-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_image_blog_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='source',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='blogs', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(default=1, upload_to='blogs', verbose_name='Video'),
            preserve_default=False,
        ),
    ]
